{"draw":1,"recordsTotal":4,"recordsFiltered":4,"data":[{"ads_id":"1","ads_name":"Advertise 4","ads_type":"Banner","ads_google":"","ads_banner":"","ads_banner_url":"http:\/\/gopiko8.cfl814.hop.clickbank.net\/","status":"Inactive","create_date":"2013-11-12","create_time":"10:59:02","advertise":"&lt;img src=&quot;..\/uploads\/ads_banner\/&quot; width=&quot;75&quot; height=&quot;100&quot; border=&quot;0&quot; style=&quot;border-color:#000000;&quot;&gt;","action":"
<a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\" data-original-title=\"Edit\" class=\"edit btn
   btn-primary btn-sm editProduct\">Edit<\/a><a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\"
                                                data-original-title=\"Delete\" class=\"btn btn-danger btn-sm
                                                deleteProduct\">Delete<\/a><a href=\"javascript:void(0)\"
                                                                              data-toggle=\"tooltip\" data-id=\"\"
                                                                              data-original-title=\"Delete\" class=\"btn
                                                                              btn-danger btn-sm
                                                                              ViewProduct\">View<\/a>","DT_RowIndex":1},{"ads_id":"2","ads_name":"Advertise 3","ads_type":"Google","ads_google":"&lt;script type=&quot;text\/javascript&quot;&gt;&lt;!--\r\ngoogle_ad_client = &quot;ca-pub-8982024490473272&quot;;\r\n\/* Gopiko_Middle *\/\r\ngoogle_ad_slot = &quot;4730936800&quot;;\r\ngoogle_ad_width = 160;\r\ngoogle_ad_height = 600;\r\n\/\/--&gt;\r\n&lt;\/script&gt;\r\n&lt;script type=&quot;text\/javascript&quot;\r\nsrc=&quot;\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js&quot;&gt;\r\n&lt;\/script&gt;","ads_banner":"","ads_banner_url":"","status":"Active","create_date":"2013-11-12","create_time":"13:33:42","advertise":"&lt;script type=&quot;text\/javascript&quot;&gt;&lt;!--\r\ngoogle_ad_client = &quot;ca-pub-8982024490473272&quot;;\r\n\/* Gopiko_Middle *\/\r\ngoogle_ad_slot = &quot;4730936800&quot;;\r\ngoogle_ad_width = 160;\r\ngoogle_ad_height = 600;\r\n\/\/--&gt;\r\n&lt;\/script&gt;\r\n&lt;script type=&quot;text\/javascript&quot;\r\nsrc=&quot;\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js&quot;&gt;\r\n&lt;\/script&gt;","action":"
<a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\" data-original-title=\"Edit\" class=\"edit btn
   btn-primary btn-sm editProduct\">Edit<\/a><a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\"
                                                data-original-title=\"Delete\" class=\"btn btn-danger btn-sm
                                                deleteProduct\">Delete<\/a><a href=\"javascript:void(0)\"
                                                                              data-toggle=\"tooltip\" data-id=\"\"
                                                                              data-original-title=\"Delete\" class=\"btn
                                                                              btn-danger btn-sm
                                                                              ViewProduct\">View<\/a>","DT_RowIndex":2},{"ads_id":"3","ads_name":"Advertise 2","ads_type":"Google","ads_google":"&lt;script type=&quot;text\/javascript&quot;&gt;&lt;!--\r\ngoogle_ad_client = &quot;ca-pub-8982024490473272&quot;;\r\n\/* Gopiko_Ad1 *\/\r\ngoogle_ad_slot = &quot;1087969603&quot;;\r\ngoogle_ad_width = 160;\r\ngoogle_ad_height = 600;\r\n\/\/--&gt;\r\n&lt;\/script&gt;\r\n&lt;script type=&quot;text\/javascript&quot;\r\nsrc=&quot;\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js&quot;&gt;\r\n&lt;\/script&gt;","ads_banner":"","ads_banner_url":"","status":"Active","create_date":"2013-11-12","create_time":"13:35:32","advertise":"&lt;script type=&quot;text\/javascript&quot;&gt;&lt;!--\r\ngoogle_ad_client = &quot;ca-pub-8982024490473272&quot;;\r\n\/* Gopiko_Ad1 *\/\r\ngoogle_ad_slot = &quot;1087969603&quot;;\r\ngoogle_ad_width = 160;\r\ngoogle_ad_height = 600;\r\n\/\/--&gt;\r\n&lt;\/script&gt;\r\n&lt;script type=&quot;text\/javascript&quot;\r\nsrc=&quot;\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js&quot;&gt;\r\n&lt;\/script&gt;","action":"
<a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\" data-original-title=\"Edit\" class=\"edit btn
   btn-primary btn-sm editProduct\">Edit<\/a><a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\"
                                                data-original-title=\"Delete\" class=\"btn btn-danger btn-sm
                                                deleteProduct\">Delete<\/a><a href=\"javascript:void(0)\"
                                                                              data-toggle=\"tooltip\" data-id=\"\"
                                                                              data-original-title=\"Delete\" class=\"btn
                                                                              btn-danger btn-sm
                                                                              ViewProduct\">View<\/a>","DT_RowIndex":3},{"ads_id":"4","ads_name":"Advertise 1","ads_type":"Banner","ads_google":"","ads_banner":"4C2332CBBX-20131112-090837.png","ads_banner_url":"http:\/\/gopiko8.flfenglish.hop.clickbank.net","status":"Inactive","create_date":"2013-11-12","create_time":"13:38:37","advertise":"&lt;img src=&quot;..\/uploads\/ads_banner\/4C2332CBBX-20131112-090837.png&quot; width=&quot;75&quot; height=&quot;100&quot; border=&quot;0&quot; style=&quot;border-color:#000000;&quot;&gt;","action":"
<a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\" data-original-title=\"Edit\" class=\"edit btn
   btn-primary btn-sm editProduct\">Edit<\/a><a href=\"javascript:void(0)\" data-toggle=\"tooltip\" data-id=\"\"
                                                data-original-title=\"Delete\" class=\"btn btn-danger btn-sm
                                                deleteProduct\">Delete<\/a><a href=\"javascript:void(0)\"
                                                                              data-toggle=\"tooltip\" data-id=\"\"
                                                                              data-original-title=\"Delete\" class=\"btn
                                                                              btn-danger btn-sm
                                                                              ViewProduct\">View<\/a>","DT_RowIndex":4}],"input":{"draw":"1","columns":[{"data":"DT_RowIndex","name":"DT_RowIndex","searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"advertise","name":"advertise","searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"status","name":"status","searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"action","name":"action","searchable":"false","orderable":"false","search":{"value":null,"regex":"false"}}],"order":[{"column":"0","dir":"asc"}],"start":"0","length":"10","search":{"value":null,"regex":"false"},"_":"1581738403968"}}
